
# DMZ 
nginx reverse  proxy  kurulacak. 

dnf install epel-release -y
dnf install nginx -y
systemctl enable --now nginx

firewall-cmd --permanent --add-service=http
firewall-cmd --permanent --add-service=https
firewall-cmd --reload

setsebool -P httpd_can_network_connect 1

vim /etc/nginx/conf.d/app.conf

```vim
server {
    listen 80;
    server_name [uygulaman.com veya DMZ IP];

    location / {
        proxy_pass http://192.168.100.x:18080; # APP Sunucusu IP'si
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
```